{% set name = "libtiledb-sql" %}
{% set version = "0.8.2" %}
{% set sha256 = "2032f68898e86f23cc6c5e43d766413464c7030492fdc71c2ebb2039be26de36" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: TileDB-MariaDB-{{ version }}.tar.gz
  url: https://github.com/TileDB-Inc/TileDB-MariaDB/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3
  skip: true  # [win]
  missing_dso_whitelist:
    - /usr/lib/libncurses.5.4.dylib  # [osx]

requirements:
  build:
    - cmake
    - pkg-config  # [not win]
    - wget  # [unix]
    - git
    - libiconv  # [osx]
    - {{ compiler('cxx') }}
  host:
    - openssl
    - libaio  # [linux]
    - libiconv  # [osx]
    - tiledb 2.2.*
    - curl
    - bison
    - zlib
    - bzip2
    - zstd
    - lz4-c
    - libedit
    - ncurses
    - xz
    - krb5
  run:
    - openssl
    - libaio  # [linux]
    - libiconv  # [osx]
    - tiledb 2.2.*
    - curl
    - bison
    - zlib
    - bzip2
    - zstd
    - lz4-c
    - libedit
    - ncurses
    - xz
    - krb5

test:
  commands:

    - test -e $PREFIX/lib/libmariadb$SHLIB_EXT  # [linux]
    - test -e $PREFIX/lib/libmariadbd$SHLIB_EXT  # [linux]
    - test -e $PREFIX/lib/libmariadb$SHLIB_EXT  # [osx]
    - test -e $PREFIX/lib/libmariadbd$SHLIB_EXT  # [osx]
    - test -e $PREFIX/bin/mysql_config  # [unix]

about:
  home: https://tiledb.com
  license: GPL-2.0-only
  license_family: GPL
  license_file: COPYING
  summary: libtiledb-sql is a SQL interface for TileDB arrays using the MyTile storage engine
  description: |
    MyTile is a storage engine for MariaDB which allows dynamic access to TileDB array. libtiledb-sql is a limited build of mariadb to produce a minimum embeddable library for a SQL interface.\n

    Docs: https://docs.tiledb.com/developer/api-usage/embedded-sql

    Source: https://github.com/TileDB-Inc/TileDB-MariaDB

    Upstream source: https://mariadb.org

  doc_url: https://docs.tiledb.com/developer/api-usage/embedded-sql
  dev_url: https://github.com/TileDB-Inc/TileDB-MariaDB

extra:
  recipe-maintainers:
    - shelnutt2
    - ihnorton
