{% set name = "libtiledb-sql" %}
{% set version = "0.4.1" %}
{% set sha256 = "6f636ca3c5192e1f2d811c14678d17aad44f0961cc4b2a9c3061ac2d02e734e2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: TileDB-MariaDB-{{ version }}.tar.gz
  url: https://github.com/TileDB-Inc/TileDB-MariaDB/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win]
  missing_dso_whitelist:
    - /usr/lib/libncurses.5.4.dylib  # [osx]

requirements:
  build:
    - cmake
    - pkg-config  # [not win]
    - wget  # [unix]
    - git
    - libiconv  # [osx]
    - {{ compiler('cxx') }}
  host:
    - openssl
    - libaio  # [linux]
    - libiconv  # [osx]
    - tiledb 1.7.*
    - curl
    - bison
    - zlib
    - bzip2
    - zstd
    - lz4-c
    - libedit
    - ncurses
    - xz
    - krb5
  run:
    - openssl
    - libaio  # [linux]
    - libiconv  # [osx]
    - tiledb 1.7.*
    - curl
    - bison
    - zlib
    - bzip2
    - zstd
    - lz4-c
    - libedit
    - ncurses
    - xz
    - krb5

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

    - test -e $PREFIX/lib/libmariadb$SHLIB_EXT  # [linux]
    - test -e $PREFIX/lib/libmariadbd$SHLIB_EXT  # [linux]
    - test -e $PREFIX/lib/libmariadb$SHLIB_EXT  # [osx]
    - test -e $PREFIX/lib/libmariadbd$SHLIB_EXT  # [osx]
    - test -e $PREFIX/bin/mysql_config  # [unix]

about:
  home: https://tiledb.com
  license: GPLv2
  license_family: GPL
  license_file: COPYING
  summary: 'libtiledb-sql is a SQL interface for TileDB arrays using the MyTile storage engine'
  description: |
    MyTile is a storage engine for MariaDB which allows dynamic access to TileDB array. libtiledb-sql is a limited build of mariadb to produce a minimum embeddable library for a SQL interface.\n
    
    Docs: https://docs.tiledb.com/developer/api-usage/embedded-sql

    Source: https://github.com/TileDB-Inc/TileDB-MariaDB
    
    Upstream source: https://mariadb.org

  doc_url: https://docs.tiledb.com/developer/api-usage/embedded-sql
  dev_url: https://github.com/TileDB-Inc/TileDB-MariaDB

extra:
  recipe-maintainers:
    - shelnutt2
    - tdenniston
    - ihnorton
