provider:
  linux_aarch64: default
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
upload_on_branch: main
test: native_and_emulated
